name: Deploy CBS Next.js App to AWS Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies and Build
        run: |
          npm ci
          npm run build
          npm run export

      - name: Rename export output directory
        run: mv ./out ./cbs-frontend

      - name: Copy Files to Lightsail
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          source: ./cbs-frontend/
          target: ~/deploy-temp/

      - name: Deploy on Lightsail
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          script: |
            sudo rm -rf /var/www/html/cbs-frontend
            sudo mv ~/deploy-temp/* /var/www/html/
            sudo rm -rf ~/deploy-temp
            sudo systemctl restart nginx
