name: Deploy CBS Static Next.js App to AWS Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies and Build Static Site
        run: |
          npm ci
          npm run build  # Will output static site to ./out because output: 'export' is set

      - name: Rename output directory
        run: mv ./out ./cbs-frontend

      - name: Upload Static Files to AWS Lightsail
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          source: ./cbs-frontend/
          target: ~/deploy-temp/

      - name: Deploy Static Site on Lightsail
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          script: |
            sudo rm -rf /var/www/html/*
            sudo mv ~/deploy-temp/* /var/www/html/
            sudo rm -rf ~/deploy-temp
            sudo systemctl restart nginx
