name: Deploy CBS Next.js App to AWS Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies and Build
        run: |
          npm ci
          npm run build

      - name: Copy Project to Lightsail
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          source: "."
          target: "~/cbs-nextjs-temp"

      - name: Deploy on Lightsail
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          script: |
            rm -rf ~/cbs-nextjs
            mv ~/cbs-nextjs-temp ~/cbs-nextjs
            cd ~/cbs-nextjs
            npm ci
            pm2 delete cbs-nextjs || true
            pm2 start npm --name "cbs-nextjs" -- start
            pm2 save
